### ISSUE TITLE
A few changes in handler.py template

### ISSUE THREAD

**Issue by weaversam8** [mkdocstrings/handler-template#1]
Hi there, this template is very helpful! Looking forward to building a custom handler!

I noticed a few discrepencies in my generated `handler.py`, I believe there are some changes needed in [`handler.py.jinja`](https://github.com/mkdocstrings/handler-template/blob/1978f7a778fbd04c75bb2646317eafcf85cf3b9d/project/src/mkdocstrings_handlers/%7B%7Bpython_package_import_name%7D%7D/handler.py.jinja)

- [x] The comment on Line 1 still has `Python` hardcoded, I believe this should be `{{ language|title }}`

   https://github.com/mkdocstrings/handler-template/blob/1978f7a778fbd04c75bb2646317eafcf85cf3b9d/project/src/mkdocstrings_handlers/%7B%7Bpython_package_import_name%7D%7D/handler.py.jinja#L1

- [x] The class name generated will fail if the user enters spaces in the language name. I would have PRed a fix for both of these, but I wasn't sure what Jinja filter to use to transform a name like `"Language Name"` to `LanguageName`

   https://github.com/mkdocstrings/handler-template/blob/1978f7a778fbd04c75bb2646317eafcf85cf3b9d/project/src/mkdocstrings_handlers/%7B%7Bpython_package_import_name%7D%7D/handler.py.jinja#L16

**Comment by pawamoy** [comment]
Hey there! Looking forward to see what you do with it :smile:!

1. Good catch. You're right.
2. Good catch as well. Getting rid of spaces should be easy enough: `{{ language.title().replace(" ", "") }}` (it's important to use `title` first, otherwise we would lose any subsequent capital letter).

Would you like to open a PR fixing these two items?
